# Используем легковесный образ Node.js
FROM node:18-alpine

# Создаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем остальные файлы приложения
COPY . .

# Сборка проекта (генерация production-сборки)
RUN npm run build

# Устанавливаем переменные окружения для приложения
ENV NODE_ENV production
ENV HOST 0.0.0.0
ENV PORT 1337

# Открываем порт
EXPOSE 1337

# Команда для запуска Strapi
CMD ["npm", "run", "start"]
