# Используем образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем весь код проекта
COPY . .

# Собираем проект
RUN npm run build

# Устанавливаем переменные окружения
ENV NODE_ENV production
ENV PORT 1337
ENV HOST 0.0.0.0

# Открываем порт для приложения
EXPOSE 1337

# Запускаем Strapi
CMD ["strapi", "start", "--host", "0.0.0.0", "--port", "1337"]
