app = "my-strapi-app"  # Название вашего приложения на Fly.io
primary_region = "fra"  # Регион Fly.io, например, Франкфурт

[build]
  dockerfile = "Dockerfile"  # Указываем Dockerfile для сборки

[env]
  PORT = "1337"
  HOST = "0.0.0.0"

[[services]]
  internal_port = 1337
  processes = ["app"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
